### ISSUE TITLE
DataType number is not supportet -> Error: Unrecognised schema format: undefined

### ISSUE THREAD

**Issue by mgrie** [pblabs/swaggering-mongoose#1]
The DataType number is not supportet.

Example:
https://github.com/samuxyz/movie-collection/blob/master/api/swagger/swagger.yaml
https://scotch.io/tutorials/speed-up-your-restful-api-development-in-node-js-with-swagger

DataTypes:
https://swagger.io/docs/specification/data-models/data-types/

**Comment by mgrie** [comment]
Example swagger.yaml:
https://github.com/samuxyz/movie-collection/blob/master/api/swagger/swagger.yaml

From Tutorial:
https://scotch.io/tutorials/speed-up-your-restful-api-development-in-node-js-with-swagger

**Comment by pibi** [comment]
Yep, this is a know limit, although `number` is actually supported if you add its format, like:

```
      year:
        type: number
        format: integer
```
