### ISSUE TITLE
Support for `default` property in schema

### ISSUE THREAD

**Issue by pibi** [pblabs/swaggering-mongoose#6]
Before:
```json
        "priority": {
          "type": "string",
          "x-swaggering-mongoose": {
            "default": "high"
          }          
        }
```
After:
```json
        "priority": {
          "type": "string",
          "default": "high" 
        }
```

**Comment by ChrisdeWolf** [comment]
Pull request created to support this. Solution does not do type validation between the defaultValue type and property type, not sure if that is directly needed since mongoose itself will likely throw that specific error.

**Comment by pibi** [comment]
@ChrisdeWolf I see where you are coming from. This library does some kind of validation on the swagger, but I don't think it's the main goal here. Indeed, we internally use other libraries for proper validation, such as [`swagger-cli`](https://www.npmjs.com/package/swagger-cli).
